### PR TITLE
Streamline the code

### PR DESCRIPTION
**Pull request by machenjie**

### CODE REVIEW

**Comment by LukasBanana** [comment]
Any explanations? I don't see the enhancement here.

**Comment by machenjie** [comment]
In your code, you have used an auxiliary structure to achieve this function, but it is not necessary, so I give the code which I think is more simple.

**Comment by LukasBanana** [comment]
Is there a reason, why you exchanged `std::size_t` by `unsigned int`?

**Comment by machenjie** [comment]
I just gress that people who use this function will not use index greater than 4294967295(0XFFFFFFFF), so there is no need to add the transform of the number, it take more code like "size_t(1)", in the new code, you just need use "1". If you can write less code, why don't you. :->

**Pull request closed without merging**
